version: '3.7'

services:
    db:
        image: mariadb
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: Welkom01!
    fpm:
        build: .
        volumes: 
            - '~/rest-api-example:/var/www'
        links:
            - db
    web:
        image: nginx
        volumes:
            - '~/rest-api-example/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
            - '~/rest-api-example:/var/www'
        ports:
            - "80:80"
        links: 
            - fpm